name: Deploy to prod

on:
  workflow_dispatch:
  push:
    branches:
      - test

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build docker image
        run: docker build -t dokku/activepieces:latest .
